-- =============================================================================
-- Migration: 001_init.sql
-- Description: Initial schema for the Hebrew News HUB project
-- Creates the articles table, indexes, RLS policies, and auto-cleanup function
-- =============================================================================


-- ---------------------------------------------------------------------------
-- TABLE: articles
-- Stores ingested news articles with Hebrew summaries generated by Gemini
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS articles (
    -- Primary key — random UUID so IDs are unguessable in public feeds
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Original English headline from the source feed
    title           TEXT        NOT NULL,

    -- Hebrew translation of the title (populated by Gemini, may be NULL on first insert)
    title_he        TEXT,

    -- Hebrew summary: 2–3 punchy sentences produced by Gemini (required before insert)
    summary_he      TEXT        NOT NULL,

    -- Canonical article URL — used as the deduplication key across all ingestion runs
    url             TEXT        NOT NULL UNIQUE,

    -- Human-readable source name, e.g. "The Verge", "BBC", "Haaretz"
    source          TEXT        NOT NULL,

    -- Taxonomy category — enforced by CHECK so bad data never reaches the table
    category        TEXT        NOT NULL
                    CHECK (category IN ('ai-builders', 'tech', 'economy', 'news', 'sports')),

    -- Original publish timestamp from the feed (ISO 8601 / RFC 822).
    -- Nullable because some feeds omit it or it arrives malformed.
    published_at    TIMESTAMPTZ,

    -- Wall-clock time when our ingestion pipeline inserted this row
    fetched_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Optional thumbnail / Open Graph image for the card UI
    image_url       TEXT
);

COMMENT ON TABLE  articles               IS 'Ingested news articles with Gemini-generated Hebrew summaries';
COMMENT ON COLUMN articles.title         IS 'Original English headline';
COMMENT ON COLUMN articles.title_he      IS 'Hebrew translation of the headline (Gemini, async)';
COMMENT ON COLUMN articles.summary_he    IS 'Hebrew summary, 2-3 sentences (Gemini, required)';
COMMENT ON COLUMN articles.url           IS 'Canonical article URL — deduplication key';
COMMENT ON COLUMN articles.source        IS 'Publisher name, e.g. "The Verge"';
COMMENT ON COLUMN articles.category      IS 'One of: ai-builders | tech | economy | news | sports';
COMMENT ON COLUMN articles.published_at  IS 'Original publish time from feed (nullable)';
COMMENT ON COLUMN articles.fetched_at    IS 'Ingestion timestamp — used for pruning';
COMMENT ON COLUMN articles.image_url     IS 'Thumbnail / OG image URL (nullable)';


-- ---------------------------------------------------------------------------
-- INDEXES
-- ---------------------------------------------------------------------------

-- Primary read pattern: "give me the latest N articles in category X"
-- Covers both the WHERE category = ? filter and ORDER BY fetched_at DESC
CREATE INDEX IF NOT EXISTS idx_articles_category_fetched
    ON articles (category, fetched_at DESC);

-- Used by the prune_old_articles() function to efficiently find stale rows
CREATE INDEX IF NOT EXISTS idx_articles_fetched_at
    ON articles (fetched_at DESC);

-- Explicit index for dedup lookups on url even though UNIQUE already creates one.
-- Naming it explicitly makes query plans and EXPLAIN output easier to read.
CREATE INDEX IF NOT EXISTS idx_articles_url
    ON articles (url);


-- ---------------------------------------------------------------------------
-- ROW LEVEL SECURITY (RLS)
-- ---------------------------------------------------------------------------

-- Enable RLS — without policies nothing is readable except by service_role
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;

-- Public read policy: the anonymous (anon) role can SELECT all rows.
-- This is intentional — the news feed is publicly visible, no auth required.
-- Write operations (INSERT / UPDATE / DELETE) are performed exclusively by the
-- ingestor using the service_role key, which bypasses RLS by default.
CREATE POLICY "anon_select_articles"
    ON articles
    FOR SELECT
    TO anon
    USING (true);

-- Note: service_role bypasses RLS automatically (Supabase default behaviour).
-- No explicit policy is needed for the ingestor / GitHub Actions service account.


-- ---------------------------------------------------------------------------
-- AUTO-CLEANUP: prune articles older than 7 days
-- ---------------------------------------------------------------------------

-- Function: prune_old_articles()
-- Deletes rows whose fetched_at is older than 7 days and returns the count.
CREATE OR REPLACE FUNCTION prune_old_articles()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER  -- runs with the privileges of the function owner (postgres)
AS $$
DECLARE
    deleted_count INTEGER;
BEGIN
    DELETE FROM articles
    WHERE fetched_at < NOW() - INTERVAL '7 days';

    GET DIAGNOSTICS deleted_count = ROW_COUNT;

    RAISE NOTICE 'prune_old_articles: deleted % rows older than 7 days', deleted_count;
    RETURN deleted_count;
END;
$$;

COMMENT ON FUNCTION prune_old_articles() IS
    'Deletes articles older than 7 days. Called by pg_cron daily at 04:00 UTC.';


-- ---------------------------------------------------------------------------
-- pg_cron scheduled job (OPTIONAL — requires the pg_cron extension)
--
-- To enable automatic daily cleanup:
--   1. In Supabase dashboard → Database → Extensions → enable "pg_cron"
--   2. Uncomment and run the block below in the SQL Editor (as postgres role)
--
-- SELECT cron.schedule(
--     'prune-old-articles',      -- job name (must be unique)
--     '0 4 * * *',               -- cron expression: daily at 04:00 UTC
--     $$ SELECT prune_old_articles(); $$
-- );
--
-- To verify the job was created:
--   SELECT * FROM cron.job;
--
-- To remove the job:
--   SELECT cron.unschedule('prune-old-articles');
-- ---------------------------------------------------------------------------
